### ISSUE TITLE
can't use "en-GB" as a language

### ISSUE THREAD

**Issue by cvlmtg** [tinganho/l10ns#132]
I have a project which currently use l10ns@2.2.5 where I defined "en-US", "en-GB" plus other languages. When I try to upgrade to l10ns 2.4.1 (installed both globally and locally) I get the following error on `l10ns compile`:

```
Error: E_MISSING_BUNDLE: {"locale":"en-GB"}
    at createError (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/node_modules/cldrjs/dist/cldr.js:339:11)
    at validate (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/node_modules/cldrjs/dist/cldr.js:355:10)
    at Cldr.main (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/node_modules/cldrjs/dist/cldr.js:669:3)
    at MessageFormat._readNumberFormatPatterns (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/libraries/MessageFormat/index.js:1019:40)
    at MessageFormat._readNumberFormatsData (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/libraries/MessageFormat/index.js:991:8)
    at new MessageFormat (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/libraries/MessageFormat/index.js:79:8)
    at /Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/plugins/javascript/compiler.js:210:29
    at _fulfilled (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/matteo/.nvf/installed/node-6.3.1/lib/node_modules/l10ns/node_modules/q/q.js:749:13)
```

`l10ns update` works fine, and the only way to make compilation work is to remove en-GB from the list of languages, but that's something I cannot do on this project...

thanks in advance!

**Comment by tinganho** [comment]
@cvlmtg can you confirm that l10ns@2.2.5 works? and not l10ns@2.4.1? I just want to make sure that it's not a down stream bug.

**Comment by cvlmtg** [comment]
yes, l10ns@2.2.5 works. it's what we are currently using in our project, and our watch/build scripts are explicitly calling *./node_modules/.bin/l10ns compile*

I made some tests with l10ns@2.4.1 (even on another, unrelated, project) and when I add "en-GB" to *l10ns.json* the error above appears. "en-US" gives no problems.

**Comment by tinganho** [comment]
@cvlmtg  I published a fix with `l10ns@2.4.3` could you please try it out?

**Comment by cvlmtg** [comment]
```
Error: Cannot find module 'cldr-data/main/null/numbers'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at new MessageFormat (/Users/matteo/dev/html5-app/node_modules/l10ns/libraries/MessageFormat/index.js:47:5)
    at /Users/matteo/dev/html5-app/node_modules/l10ns/plugins/javascript/compiler.js:210:29
    at _fulfilled (/Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:749:13)
    at /Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:557:44
```

**Comment by tinganho** [comment]
@cvlmtg I published newer version 2.4.4.

**Comment by cvlmtg** [comment]
my test were made with 2.4.4.
sorry I didn't notice your first message said 2.4.3 while I installed 2.4.4, so I didn't report that

```
 (develop) ~/d/html5-app npm --depth=0 ls -g | grep l10ns
├── l10ns@2.4.4
 (develop) ~/d/html5-app npm --depth=0 ls | grep l10ns
├── l10ns@2.4.4
 (develop) ~/d/html5-app ./node_modules/.bin/l10ns compile
Error: Cannot find module 'cldr-data/main/null/numbers'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at new MessageFormat (/Users/matteo/dev/html5-app/node_modules/l10ns/libraries/MessageFormat/index.js:47:5)
    at /Users/matteo/dev/html5-app/node_modules/l10ns/plugins/javascript/compiler.js:210:29
    at _fulfilled (/Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:749:13)
    at /Users/matteo/dev/html5-app/node_modules/l10ns/node_modules/q/q.js:557:44
```

**Comment by tinganho** [comment]
Lets try again with 2.4.5?

**Comment by cvlmtg** [comment]
it works! thanks :)
