### ISSUE TITLE
Error: Cannot find module 'internal/fs' after updating to node v7.0.0

### ISSUE THREAD

**Issue by sureshHARDIYA** [tinganho/l10ns#141]
After updating to node v7.0.0, all of the `l10ns` commands are throwing error. When running `l1ons interface` on my machine, I get:

```
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/l10ns/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

could get some help with it?

**Comment by tinganho** [comment]
I've got some slight problem reproduice this.
```
$ node --version
v7.0.0

$ node /usr/local/lib/node_modules/l10ns/binaries/l10ns interface
(node:21433) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
Translation interface is now available in http://localhost:3001.
Close the interface using CTRL + C.
Opening web browser...
GET / 302 5ms - 84b
(node:21433) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
GET /en-US/localizations 200 62ms
```

**Comment by tinganho** [comment]
It's probably best to wait a bit. My limited research on this bug is that it has something to do with node v7.

**Comment by sureshHARDIYA** [comment]
I moved to earlier version of node and it worked. So, best solution for now is not to update node IMO.
