### ISSUE TITLE
permission error with composer file

### ISSUE THREAD

**Issue by marcelohack** [tinganho/l10ns#88]
Hi Tinganho,

I'm getting a follow error, when i tried to run l10ns interface

Cannot find module './configurations/autoRoutes'

i've already reinstalled l10ns.

Thanks in advance,
Marcelo

**Comment by tinganho** [comment]
I've just pushed out a new version l10ns@2.0.7. Can you try it out?

**Comment by marcelohack** [comment]
Hi Tingan,

i ve made a complete uninstall, installed again, and now i'm getting the following error:

EACCES, permission denied '/usr/lib/node_modules/l10ns/interface/public/scripts/routers/composer.js'

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/usr/lib/node_modules/l10ns/interface//public/scripts/configurations/cf.js'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at /usr/lib/node_modules/l10ns/interface/core/configuration.js:124:10
    at Glob.<anonymous> (/usr/lib/node_modules/l10ns/node_modules/glob/glob.js:96:7)
    at Glob.emit (events.js:95:17)
    at Glob.next (/usr/lib/node_modules/l10ns/node_modules/glob/glob.js:343:12)
    at Glob._processEmitQueue (/usr/lib/node_modules/l10ns/node_modules/glob/glob.js:310:12)
    at Glob.emitMatch (/usr/lib/node_modules/l10ns/node_modules/glob/glob.js:290:8)
    at Glob._finish (/usr/lib/node_modules/l10ns/node_modules/glob/glob.js:230:8)
    at Glob.<anonymous> (/usr/lib/node_modules/l10ns/node_modules/glob/glob.js:183:27)


thanks,
Marcelo

**Comment by tinganho** [comment]
composer script is a compiled file, but I haven't seen it cause permission problems before. Which OS are you using?

**Comment by marcelohack** [comment]
Made an chmod -R 775 /usr/lib/node_modules/l10ns

and now is running

thanks
Marcelo

**Comment by marcelohack** [comment]
kubuntu 14.10

**Comment by marcelohack** [comment]
i've made an chmod -R 775 to the root of the package and now its working fine.

thank you

**Comment by tinganho** [comment]
OK I will try to fix this later. I don't have a ubuntu image available. Ideally you shouldn't need to chmod things.

**Comment by tinganho** [comment]
This should be fixed now.
